#!/bin/sh
usage() {
	echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

if ! sed 's/^Version:.*$/Version:        '$1'/g' php-slurm.spec > .php-slurm.spec.new; then
	echo "Could not replace PHPSLURM_VERSION variable." >&2
	exit 2
fi
mv .php-slurm.spec.new php-slurm.spec


echo php-slurm-$1 > VERSION

git add VERSION
git add php-slurm.spec
git commit -m "Bumped version number to $1"
